@startuml 任务队列 

title 任务队列发布消息处理流程

三方系统 --> 业务服务: 推送订阅的消息数据
业务服务 --> 任务队列: 发布消息
任务队列 --> 存储: 存储到数据库、内存
任务队列 --> 任务队列: 分发Message执行
任务队列 --> 存储: 执行成功，删除存储
任务队列 --> 存储: 执行失败，更新重试次数，超过重试限制，打印日志，删除存储，没有超过重试次数则存储

@enduml